---
title: "Goncalves_resposta_lista1."
author: "Moisés Gonçalves"
date: "2025-01-31"
output: pdf_document
---

# Questão 1 
```{r setup, include=FALSE}
#require(ggplot2)
library(ggplot2)

set.seed(35)

#creating variables 
beta = 0.987 # intertemporal discount rate (discrete time)

mu = 2 # risk aversion

alpha = 1/3 # income of labor/ toal income 

delta = 0.012 # depreciation rate 

rho = 0.95 # persistence of the previous shock

sigma = 0.007 # variance of the white error of the shock

tol = 10^(-5)

k_ss = (1/(alpha*beta) - (1-delta)/alpha)^(1/(alpha-1))
```

```{r}
#Tauchen function
N = 7 # number of points 
m = 3

thetas = c(1:N)


## Upper bound of theta 

thetas[N] = m*sigma/((1-rho^2)^(1/2))

## Lower bounf of theta 
thetas[1] = -thetas[N]

delta_theta = thetas[N]/((N-1)/2)

# The other theta_ns
# This calculates the value of the intermediary thetas

for (i in 2:(N-1)){
  print(i)
  thetas[i] = thetas[1] + (i-1)*delta_theta
}
transition_matrix = matrix(,N,N)
#transition_matrix


#Probability(i,j) is given theta_i the probability of theta_j being draw in the next period

for (i in 1:N){
  for (j in 1:N){
    if (j==1){
      transition_matrix[i,j] = pnorm((thetas[j] + delta_theta/2 - rho*thetas[i])/sigma)
    }else if (j==N){
      transition_matrix[i,j] = 1 - pnorm((thetas[j] - delta_theta/2 - rho*thetas[i])/sigma)
    }else{
    transition_matrix[i,j] = pnorm((thetas[j] + delta_theta/2 - rho*thetas[i])/sigma) - pnorm((thetas[j] - delta_theta/2 - rho*thetas[i])/sigma)
    }
  }
}

```

```{r}
# Question 3
# Iteration of the value function

k_grid_size = 500
k_grid = seq(from= 0.75*k_ss, to=1.25*k_ss, length.out = k_grid_size) #Create grid for capital

z_grid = thetas # The grid of the shocks 

iter =0



max_iter = 20000

V =matrix(0,k_grid_size,N)  # V_0 starts with 0, it is a matrix
#colnames(V) = c(thetas) # The V(k,z) is a vector that given a k it can assume different values depending on the realization of the shock z

#### Create a list of names theta_1 to theta_n

col_names_V = c(1:N)
for(i in 1:N){
  x= c("theta_",i)
  col_name = paste(x, collapse = "")
  col_names_V[i] = col_name   
}

colnames(V) = col_names_V


####

V_new = V
policy_k_prime = V

error_V_Vnew = 10 # initial error for the difference between V_t and V_t+1

k_prime_grid = k_grid



### Defining the utility function
u = function(c){
  if(c<0){
    return(-999)
  }
  else{
    return((c^(1-mu) -1)/(1-mu))
  }
}




###

# Brute force 


while (max_iter > iter){
  z_idx = 1
  for (z in z_grid){
    #print(paste("Whe are in z = ", z))
    k_idx = 1
    for(k in k_grid){
      #print(paste("k = ", k))
      value_try = -99
      value_try_max = value_try
      k_prime_max = 0
      
      for (k_prime in k_prime_grid){ #Here i find the k' who maximizes the value function V given k and z
        
        c = z*(k^alpha) + (1-delta)*k - k_prime
        value_try = u(c) + beta*sum(transition_matrix[z_idx,]*V[k_idx,])
        if (value_try> value_try_max){
          value_try_max = value_try
          k_prime_max = k_prime
        }
      }
      V_new[k_idx,z_idx] = value_try_max
      policy_k_prime[k_idx,z_idx] = k_prime_max
      
      k_idx = k_idx +1
    }
    z_idx = z_idx +1
  }
    error_V_Vnew =max(abs(V-V_new))
    if(error_V_Vnew<tol){
      break
    }
    V = V_new
    print(paste("iteration = ", iter))
    print(paste("error_V_Vnew = ", error_V_Vnew))
    iter = iter +1
}



```

